# Generated by Django 6.0.5 on 2026-06-05 19:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Local')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem_principal', models.ImageField(help_text='Aparece no card da listagem e como primeira foto da galeria.', upload_to='locais/capas/', verbose_name='Imagem Principal')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Local Rural',
                'verbose_name_plural': 'Locais Rurais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='locais/galeria/', verbose_name='Foto')),
                ('legenda', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Número menor aparece primeiro.', verbose_name='Ordem na galeria')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='locais.localrural', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Imagem do Local',
                'verbose_name_plural': 'Imagens do Local',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(max_length=1000, verbose_name='Comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='locais.comentario', verbose_name='Resposta a')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='locais.localrural', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(choices=[(0.5, '0.5 ★'), (1.0, '1.0 ★'), (1.5, '1.5 ★'), (2.0, '2.0 ★'), (2.5, '2.5 ★'), (3.0, '3.0 ★'), (3.5, '3.5 ★'), (4.0, '4.0 ★'), (4.5, '4.5 ★'), (5.0, '5.0 ★')], validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)], verbose_name='Nota')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='locais.localrural', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'unique_together': {('local', 'usuario')},
            },
        ),
    ]
