# Generated by Django 6.0.6 on 2026-06-09 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_codigoverificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigoverificacao',
            options={'verbose_name': 'Código de Verificação', 'verbose_name_plural': 'Códigos de Verificação'},
        ),
        migrations.RemoveField(
            model_name='codigoverificacao',
            name='expira_em',
        ),
        migrations.AlterField(
            model_name='codigoverificacao',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='codigoverificacao',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_verificacao', to=settings.AUTH_USER_MODEL),
        ),
    ]
