# Generated by Django 6.0.4 on 2026-05-18 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('categoria', models.CharField(choices=[('aviso_geral', 'Aviso Geral'), ('evento', 'Evento'), ('academico', 'Acadêmico'), ('oportunidade', 'Oportunidade'), ('extensao', 'Extensão'), ('pesquisa', 'Pesquisa'), ('manutencao', 'Manutenção'), ('urgente', 'Urgente')], default='aviso_geral', max_length=20, verbose_name='Categoria')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='mural/%Y/%m/', verbose_name='Imagem')),
                ('alt_texto', models.CharField(blank=True, help_text='Descreva a imagem para leitores de tela.', max_length=255, null=True, verbose_name='Texto Alternativo (acessibilidade)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('publicado', models.BooleanField(default=True, help_text='Desmarque para ocultar o aviso sem deletá-lo.', verbose_name='Publicado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
