# Generated by Django 6.0.5 on 2026-05-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='titulo',
            field=models.CharField(default='', max_length=150, verbose_name='Título'),
        ),
    ]
