# Generated by Django 6.0.5 on 2026-06-09 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0002_aviso_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Descreva o acontecimento ou pauta que deseja sugerir.', verbose_name='Texto da Sugestão')),
                ('categoria', models.CharField(choices=[('aviso_geral', 'Aviso Geral'), ('evento', 'Evento'), ('academico', 'Acadêmico'), ('oportunidade', 'Oportunidade'), ('extensao', 'Extensão'), ('pesquisa', 'Pesquisa'), ('manutencao', 'Manutenção'), ('urgente', 'Urgente')], default='aviso_geral', max_length=20, verbose_name='Categoria Sugerida')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('negada', 'Negada')], default='pendente', max_length=10, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('arquivado_em', models.DateTimeField(blank=True, help_text='Preenchido automaticamente ao negar.', null=True, verbose_name='Arquivado em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Sugestão',
                'verbose_name_plural': 'Sugestões',
                'ordering': ['-criado_em'],
            },
        ),
    ]
